env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "XIdCUkf_gdOjUY9wseHEDQ"

addons:
  coverity_scan:
    project:
      name: "vooon/mavros"
      description: "Build submitted via Travis CI"
    notification_email: vooon341@gmail.com
    #build_command_prepend: "./configure; make clean"
    #build_command:   "make -j 4"
    branch_pattern: coverity_scan
