language: cpp
script: "echo 'No build jobs for travis, its done by ros buildfarm, but i want coverity scan'"
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ORA0MsiEB+R3pk8qKFRllVDK7eEQGo0LoRy6VtdyU0SOw00lEWCSD8FFJM922H5e18ZME9fIfc0ttKvbEhRwPx/AUCME+0lLkcHmogc7UyB8Gu6yqXfcp0XLVKPeLK/9+9geFmb5v9P0CH3cX4PYzimzt1ay0BVfomXX4+NkipE="

addons:
  coverity_scan:
    project:
      name: "vooon/mavros"
      description: "Build submitted via Travis CI"
    notification_email: vooon341@gmail.com
    build_command_prepend: "cmake ."
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
